### ISSUE TITLE
Create lambda function to get movie details

### ISSUE THREAD

**Issue by maxwfreu** [maxwfreu/WatchItWednesday#2]
We need a lambda function that grabs the movie details for a given week

## Endpoint requirements
- Params: 
   - A Wednesday (date? timestamp?)
- Returns
   - movie details for that Wednesday
   ```
   movies: [
     {
        title: string,
        director: string,
        cast: Array of strings,
        plot: string,
        ratings: string, // Rotten Tomatoes or whatever
        posterURL: string (url),
        isSuggestedMove: bool, // This is the movie that will appear first
     },
     ...
   ]
   ```

## Tasks
- [ ] Create AWS account
- [ ] Setup lambda function
- [ ] Setup Database
- [ ] Assign correct security groups
